version: '3'

services:
  webui-privaxy:
    container_name: webui-privaxy
    volumes:
      - $HOME/.cache/webui-privaxy:/.cache/webui-privaxy
    image: ghcr.io/deetungsten/webui-privaxy:latest
    network_mode: "host"
    environment:
      - IP_ADDRESS=0.0.0.0